FROM gone/php:cli

RUN mkdir /composer
ENV COMPOSER_HOME=/composer

RUN composer global require \
        phpstan/phpstan\
        phpstan/extension-installer \
        phpstan/phpstan-doctrine \
        phpstan/phpstan-phpunit \
        phpstan/phpstan-nette \
        phpstan/phpstan-symfony \
        phpstan/phpstan-mockery \
        phpstan/phpstan-webmozart-assert \
    && composer global show "*phpstan*" \
    && composer --version

COPY github-actions/phpstan.sh /phpstan.sh
ENTRYPOINT ["/phpstan.sh"]
