name: Build Extended Images

on:
  push:
  schedule:
    - cron: '0 7 * * TUE'

jobs:
  lint:
    name: Lint Dockerfiles
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Lint docker files
        uses: docker://cdssnc/docker-lint

  github-actions-phpstan:
    name: Github Actions => PHPStan
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-qemu-action@v1
        name: Setup QEmu
      - uses: docker/setup-buildx-action@v1
        name: Setup Docker Buildx
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: gone/github-actions:phpstan
          file: Dockerfile.Github-Action-PHPStan

  github-actions-phpcs:
    name: Github Actions => PHPCS
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-qemu-action@v1
        name: Setup QEmu
      - uses: docker/setup-buildx-action@v1
        name: Setup Docker Buildx
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: gone/github-actions:phpstan
          file: Dockerfile.Github-Action-PHPStan